[package]
name = "rs_cms"
version = "0.1.0"
authors = ["grv07 <grvtyagi22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
syn = "*"
quote = "*"
